debug

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -11,7 +11,7 @@ after_success:
     n=`grep -ce "\* org.scala-lang" sbt.log`
     echo $?
     echo $n
-    n==0
+    if (n==0); then echo "ERROR: Found conflicting dependencies inside biopet"; exit 1; fi
 #    || \
 #    (echo "ERROR: Found conflicting dependencies inside biopet" && exit 1)
   - "git diff --exit-code || (echo ERROR: Git changes detected, please regenerate the readme, create license headers and run scalafmt with: sbt biopetGenerateReadme headerCreate scalafmt && exit 1)"
